# Generated by Django 4.2.2 on 2023-06-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
