"""Your migration message

Revision ID: 76a90f4612d8
Revises: a6dd365d57bb
Create Date: 2023-06-03 23:30:24.220455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76a90f4612d8'
down_revision = 'a6dd365d57bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ActorMovie', 'actor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ActorMovie', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('Actors', sa.Column('bio_url', sa.String(length=255), nullable=True))
    op.alter_column('MovieGenre', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('MovieGenre', 'genre_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('Rating', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Rating', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('MovieGenre', 'genre_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('MovieGenre', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('Actors', 'bio_url')
    op.alter_column('ActorMovie', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ActorMovie', 'actor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
