"""test

Revision ID: 967d0f484219
Revises: ae5e0fac7a3e
Create Date: 2023-06-04 01:00:31.256385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967d0f484219'
down_revision = 'ae5e0fac7a3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
