"""Your migration message

Revision ID: ae5e0fac7a3e
Revises: 76a90f4612d8
Create Date: 2023-06-04 00:29:38.857295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5e0fac7a3e'
down_revision = '76a90f4612d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
