"""empty message

Revision ID: b4b174d35334
Revises: fc7999d44e29
Create Date: 2023-06-04 01:51:29.167940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4b174d35334'
down_revision = 'fc7999d44e29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Award', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Award', 'movie_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
